### ISSUE TITLE
Inspiration for UI

### ISSUE THREAD

**Issue by ktk** [zazuko/swiss-archival-institutions#37]
Someone which was at #archiveCH contacted me and pointed me to her bachelor thesis:

> Die Schwierigkeiten bei der Recherche im Archiv(-katalog). Ursachenforschung und Vorschläge zur Problemstellung

http://www.htwchur.ch/uploads/media/CSI_74_Mueller.pdf

Could be great input for us

**Comment by l00mi** [comment]
This issue was moved to zazuko/zack-search#8
